pipeline{

agent any

stages {

stage('Build Application') {

steps {

sh 'mvn clean install'

}
}
stage('Deploy CloudHubs') {

environment {
ANYPOINT_CREDENTIALS = credentials('')

}

steps {

echo 'Deploying mule project due to the latest code commit…'

echo 'Deploying to the configured environment….'

sh 'mvn clean deploy -DmuleDeploy  -Dusername=${Jtrip23} -Dpassword=${2018Hw86680} -DworkerType=Micro -Dworkers=1 -Denv=SANDBOX -Dsecure.key=******'

}

}
}
}
